name: dev my app

on:
  push:
    branches:
      - develop

concurrency:
  group: dev-my-app
  cancel-in-progress: true

env:
  PHASE: dev
  APP_NAME: my-app
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_CODE_DEPLOY_NAME: ${{ secrets.AWS_CODE_DEPLOY_NAME }}
  AWS_CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 2. Checkout Code
        uses: actions/checkout@v4

      - name: 3. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: samplerolesession

      - name: 4. Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 5. Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_PRIVATE_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.dev -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo "${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}" > image.txt
          echo "${{ env.REGISTRY }}/${{ env.REPOSITORY }}" > ecr-url.txt

  push_and_deploy:
    runs-on: ubuntu-22.04
    needs: build  # push와 deploy는 build가 끝난 후 실행됩니다
    steps:
      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: samplerolesession

      - name: 3. Push Docker image to ECR
        run: |
          REGISTRY=$(cat ecr-url.txt)
          IMAGE_TAG=$(cat image.txt)
          docker push $REGISTRY:$IMAGE_TAG

      - name: 4. Create a ZIP file for AWS CodeDeploy
        run: |
          mkdir ${{env.AWS_CODE_DEPLOY_NAME}} && cp -r appspec.yml image.txt ecr-url.txt ${{ env.AWS_CODE_DEPLOY_NAME }}
          mkdir ${{env.AWS_CODE_DEPLOY_NAME}}/scripts && cp -r deploy.sh ${{ env.AWS_CODE_DEPLOY_NAME }}/scripts

      - name: 5. Upload ZIP file to S3 (for CodeDeploy)
        run: |
          aws deploy push \
          --application-name ${{env.AWS_CODE_DEPLOY_NAME}} \
          --s3-location s3://${{env.AWS_S3_BUCKET_NAME}}/codedeploy/$GITHUB_SHA.zip \
          --ignore-hidden-files \
          --source ${{env.AWS_CODE_DEPLOY_NAME}}

      - name: 6. Deploy to EC2 using AWS CodeDeploy
        run: |
          echo "Deploying the application"
          aws deploy create-deployment --application-name ${{env.AWS_CODE_DEPLOY_NAME}} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{env.AWS_CODE_DEPLOY_GROUP}} \
          --s3-location bucket=$AWS_S3_BUCKET_NAME,bundleType=zip,key=codedeploy/$GITHUB_SHA.zip